### ISSUE TITLE
Add static DNS server migration

### ISSUE THREAD

**Issue by jcronenberg** [jcronenberg/agama#34]
Previous discussion revealed that probably a full migration isn't possible (e.g. `NETCONFIG_DNS_POLICY="STATIC_FALLBACK"` isn't possible with NetworkManager).
But e.g. `NETCONFIG_DNS_STATIC_SERVERS` should be migrated.

**Comment by jcronenberg** [comment]
As for the implementation, AFAICT Netconfig isn't represented inside `wicked show-config`, so we'll need to implement a way to read `/etc/sysconfig/config` via e.g. https://github.com/dotenv-rs/dotenv

**Comment by jcronenberg** [comment]
The way I see it there are basically 2 possibilities to 'imitate' the netconfig behavior for NM.  
A global DNS server configuration or adding the DNS servers to every connection in the `ipv*.dns` property.  
Here's what I think some of the advantages and disadvantages for these are:

### Global DNS

Pros:
- The closest to the netconfig behavior
- Maps better to what is actually written in `/etc/resolv.conf`
- IMO better for servers where a lot of connections are more common and changing them globally simultaneously is more important

Cons:
- Requires a configuration file either in `/etc/NetworkManager/conf.d` or `/var/lib/NetworkManager/NetworkManager-intern.conf`
- Due to configuration file changes on a running system this requires a NM restart to take effect
- This setting isn't accessible by nmcli only via DBUS

### Setting DNS for every connection

Pros:
- IMO seems to be the NM 'way' at least from what I read online, so what users may be used to.
- IMO better for clients/simple setups where single connections are more common and changing quickly via nmcli is more important

Cons:
- Tedious to change DNS servers for all connections
- If single connections are changed it is not transparent what gets actually written to `/etc/resolv.conf`. It seems NM chooses DNS servers based on some priority setting, which we won't set for the migration. So when a single connection is changed I personally don't know what actually happens.

For #75 I chose the global DNS config approach because I personally think it's the better option but changing it to the other approach can be done relatively quickly, so it's no problem if we choose differently in the end.

**Comment by cfconrad** [comment]
> Due to configuration file changes on a running system this requires a NM restart to take effect

It looks like there is a way to reread only the dns-configuration https://gitlab.freedesktop.org/NetworkManager/NetworkManager/blob/main/src/nmcli/general.c#L350

**Comment by cfconrad** [comment]
This enum somehow explain quite good what `NetworkManager` does: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/blob/main/src/core/dns/nm-dns-manager.h#L101
