### ISSUE TITLE
Add support for firewall

### ISSUE THREAD

**Issue by jcronenberg** [jcronenberg/agama#64]

**Comment by cfconrad** [comment]
>  How does firewalld work with NM?
there is the possibility to define the firewall-zone in NetworkManager (like we have with wicked) `connection.zone`
```The trust level of a the connection. Free form case-insensitive string (for example "Home", "Work", "Public"). NULL or unspecified zone means the connection will be placed in the default zone as defined by the firewall. When updating this property on a currently activated connection, the change takes effect immediately.```

>  How does firewall-cmd write the firewall zones into ifcfg files?
It's an upstream feature: https://github.com/firewalld/firewalld/blob/main/src/firewall/core/fw_ifcfg.py#L48
And called on permanent changes:
  * `--runtime-to-permanent` https://github.com/firewalld/firewalld/blob/main/src/firewall/server/firewalld.py#L525
  * `--permanent --add-interface XXX --zone=YYY` https://github.com/firewalld/firewalld/blob/main/src/firewall/server/config_zone.py#L965
  * `--permanent --remove-interface XXX --zone=YYY` https://github.com/firewalld/firewalld/blob/main/src/firewall/server/config_zone.py#L979

>  Do we really need to migrate something?
Yes, let's set the firewall-zone as we have it in wicked-xml
